GET http://localhost:5041/customers

###
GET http://localhost:5041/customers/90d89b14-ded2-4363-b5f0-8d08e4f3dc14

###
POST http://localhost:5041/customers
Content-Type: application/json

{
  "gitHubUsername": "user123",
  "fullName": "username123",
  "email": "email@example.com"
}

###
PUT http://localhost:5041/customers/de4addca-25a8-40c4-bdd3-ed9d43110792
Content-Type: application/json

{
  "guid": "de4addca-25a8-40c4-bdd3-ed9d43110792",
  "gitHubUsername": "55555",
  "email": ""
}

###
DELETE http://localhost:5041/customers/fe31f1ce-1593-4314-9d04-133928e4ff20