GET http://localhost:5041/customers

###
GET http://localhost:5041/customers/5988551f-c766-49fd-8627-e57b9c5e1b8c

###
POST http://localhost:5041/customers
Content-Type: application/json

{
  "gitHubUsername": "user123",
  "fullName": "username123",
  "email": "email@example.com"
}

###
PUT http://localhost:5041/put

###
DELETE http://localhost:5041/delete